### Two Dimensionla Array
Two dimensional array is an array within an array. It is an array of arrays. In this type of array the position of an data element is referred by two indices instead of one. So it represents a table with rows an dcolumns of data. In the below example of a two dimensional array, observer that each array element itself is also an array.

<b>Consider the example of recording temperatures 4 times a day, every day. Some times the recording instrument may be faulty and we fail to record data. Such data for 4 days can be presented as a two dimensional array as below</b>

Day 1 - 11 12 5 2<br>
Day 2 - 15 6 10 <br>
Day 3 - 10 8 12 5 <br>
Day 4 - 12 15 8 6<br>

<b>The above data can be represented as a two dimensional array as below.</b><br>

In [1]:
arr_2d = [[11, 12, 5, 2], [15, 6,10], [10, 8, 12, 5], [12,15,8,6]]

In [2]:
print(arr_2d)

[[11, 12, 5, 2], [15, 6, 10], [10, 8, 12, 5], [12, 15, 8, 6]]


In [3]:
# Row access
print(arr_2d[0])

[11, 12, 5, 2]


In [4]:
print(arr_2d[1])

[15, 6, 10]


In [5]:
print(arr_2d[3])

[12, 15, 8, 6]


In [6]:
# prinr elenment
print(arr_2d[0][0]) # [R][C] R->Row and C->column

11


In [8]:
# prinr elenment
print(arr_2d[0][1]) #[R][C] R->Row and C->column

12


In [9]:
# prinr elenment
print(arr_2d[1][0]) # [R][C] R->Row and C->column

15


In [11]:
# Prinr whole arr_2d in 2D form
for row in arr_2d:
    for col in row:
        print(col, end = " ")
    print()

11 12 5 2 
15 6 10 
10 8 12 5 
12 15 8 6 


<b>Declare 2D List taking Input by user</b>

In [31]:
row = int(input())
col = int(input())
li_2d = []
for r in range(row):
    a = []
    for c in range(col):
        a.append(int(input()))
    li_2d.append(a)
    
for r in range(row):
    for c in range(col):
        print(li_2d[r][c], end = " ")
    print()

3
3
1
2
3
4
5
6
7
8
9
1 2 3 
4 5 6 
7 8 9 


<b> Access an element in 2D array </b>

In [32]:
print(li_2d[0][2])

3


In [33]:
print(li_2d[2][2])

9


In [34]:
li_2d[0][0]=3

In [35]:
for r in range(row):
    for c in range(col):
        print(li_2d[r][c], end = " ")
    print()

3 2 3 
4 5 6 
7 8 9 


In [37]:
sum = 0
for r in range(row):
    for c in range(col):
        sum+=li_2d[r][c]
print(sum)

47


<b> Another way to inetialization of an 2D array</b>

In [43]:
import numpy as np
row = int(input())
col = int(input())

ele = list(map(int,input().split()))
matrix = np.array(ele).reshape(row,col)
print(matrix)

3
3
1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


<b> Access an element in 2D array </b>

In [44]:
print(ele[1])

2


In [45]:
print(ele[3])

4


In [46]:
ele[1] = 10
ele[3] = 21

In [48]:
matrix = np.array(ele).reshape(row,col)
print(matrix)

[[ 1 10  3]
 [21  5  6]
 [ 7  8  9]]


### List Comprehension
Python provides compact syntax for deriving one list from another. These expressions are called list comprehensions.List comprehensions are one of the most powerful tools in Python. Python’s list comprehension is an example of the language’s support for functional programming concepts.
The Python list comprehensions are a very easy way to apply a function or filter to a list of items. List comprehensions can be very useful if used correctly but very unreadable if you're not careful.

<b>Syntax</b>
The general syntax of list comprehensions is −

<b>[expr for element in iterable if condition]</b>

In [60]:
# for eg. we have to find squre of ele
li = [1,2,3,4]
li_new = []
for ele in li:
    li_new.append(ele**2)
print(li_new)

[1, 4, 9, 16]


In [63]:
# Apply List Comprehension in one line
li_new_c = [ele**2 for ele in li]
print(li_new_c)

[1, 4, 9, 16]


In [66]:
# Let's find square on an even ele
li_even_square = [ele**2 for ele in li if ele%2==0]
print(li_even_square)

[4, 16]


In [68]:
# without List comprehention 
li_even_sq = []
for ele in li:
    if ele%2==0:
        li_even_sq.append(ele**2)
print(li_even_sq)

[4, 16]


In [74]:
# without using list comprehension 
li_c = [1,2,3,4,5,6,7,8,9,]
li_n = []
for ele in li_c:
    if ele%2==0:
        if ele%3==0:
            li_n.append(ele)
print(li_n)
            

[6]


In [75]:
# append the element which is mutiple of 2 and 3 
li = [1,2,3,4,5,6,7,8,9]
li_new = [ele for ele in li if ele%2==0 if ele%3==0]
print(li_new)

[6]


In [78]:
# let's find Intersection
li1 = [1,2,3,4,5]
li2 = [2,4,6,7]
li_inter = []
for ele1 in li1:
    for ele2 in li2:
        if ele1==ele2:
            li_inter.append(ele1)   
print(li_inter)

[2, 4]


In [82]:
# Let'd do same tjing by using List comprehention
li1 = [1,2,3,4,5]
li2 = [2,4,6,7]
li_inter = [ele1 for ele1 in li1 for ele2 in li2 if ele1==ele2]
print(li_inter)

[2, 4]


In [85]:
# if multiple of 2 the do square if not do nothing
li = [1,2,3,4,5,6]
li_n =[]
for ele in li:
    if ele%2==0:
        li_n.append(ele**2)
    else:
        li_n.append(ele)
        
print(li_n)

[1, 4, 3, 16, 5, 36]


In [87]:
# let's do same thing using list comprehension
li = [1,2,3,4,5,6]
li_n = [ele**2 if ele%2==0 else ele for ele in li]
print(li_n)

[1, 4, 3, 16, 5, 36]


In [88]:
# List comprehension in string
s = "Deepak"
li = [ele for ele in s]
print(li)

['D', 'e', 'e', 'p', 'a', 'k']


In [90]:
li = ["Deepak", "Gyan", "Aman"]
li_2d = [[s for s in ele] for ele in li]
print(li_2d)

[['D', 'e', 'e', 'p', 'a', 'k'], ['G', 'y', 'a', 'n'], ['A', 'm', 'a', 'n']]


<b> Taking Input an Array unig List Comprehension</b>

In [91]:
str = input().split()
n,m = int(str[0]),int(str[1])
li_2d = [[int(j) for j in  input().split()] for i in range(n)]

3 3
1 2 3
4 5 6
7 8 9


<b> Jagged List</b><br>
A jagged array in Python is pretty much a list of lists as you stduied. in which coloumn size is not fixed

In [92]:
n = int(input())
li_2d = [[int(j) for j in  input().split()] for i in range(n)]

3
1 2 3
2 3
7 8 9 6


<b> Some Qus for peactices </b>

In [8]:
# Find Row wise sum
str = input().split()
n,m = int(str[0]),int(str[1])
li_2d = [[int(j) for j in  input().split()] for i in range(n)]
    
for r in range(n):
    sum = 0
    for c in range(m):
        sum+=li_2d[r][c]
    print(sum, end =" ")
   

3 3
1 2 3
4 5 6
7 8 9
6 15 24 

In [9]:
# Find column wise max sum
str = input().split()
n,m = int(str[0]),int(str[1])
li_2d = [[int(j) for j in  input().split()] for i in range(n)]
print()
max = -1
for c in range(m):
    sum = 0
    for r in range(n):
        sum+=li_2d[r][c]
        if sum>max:
            max = sum
print(max)
   

3 3
1 2 3
4 5 6
7 8 9

24


In [12]:
# Wave form
str = input().split()
n,m = int(str[0]),int(str[1])
li_2d = [[int(j) for j in  input().split()] for i in range(n)]
print()

for c in range(m):
    if c%2==0:
        for r in range(n):
            print(li_2d[r][c], end= " ")
    else:
        for r in range((n-1),-1,-1):
            print(li_2d[r][c],end= " ")
   

3 3
10 20 30
40 50 60
70 80 90

10 40 70 80 50 20 30 60 90 